IRON_HYGER_RESPONSE = {
    "skills": [
        {"id": 0, "name": "Overall", "rank": 1, "level": 2277, "xp": 4600000000},
        {"id": 1, "name": "Attack", "rank": 35, "level": 99, "xp": 200000000},
        {"id": 2, "name": "Defence", "rank": 28, "level": 99, "xp": 200000000},
        {"id": 3, "name": "Strength", "rank": 46, "level": 99, "xp": 200000000},
        {"id": 4, "name": "Hitpoints", "rank": 2, "level": 99, "xp": 200000000},
        {"id": 5, "name": "Ranged", "rank": 13, "level": 99, "xp": 200000000},
        {"id": 6, "name": "Prayer", "rank": 4, "level": 99, "xp": 200000000},
        {"id": 7, "name": "Magic", "rank": 1, "level": 99, "xp": 200000000},
        {"id": 8, "name": "Cooking", "rank": 31, "level": 99, "xp": 200000000},
        {"id": 9, "name": "Woodcutting", "rank": 34, "level": 99, "xp": 200000000},
        {"id": 10, "name": "Fletching", "rank": 9, "level": 99, "xp": 200000000},
        {"id": 11, "name": "Fishing", "rank": 21, "level": 99, "xp": 200000000},
        {"id": 12, "name": "Firemaking", "rank": 190, "level": 99, "xp": 200000000},
        {"id": 13, "name": "Crafting", "rank": 5, "level": 99, "xp": 200000000},
        {"id": 14, "name": "Smithing", "rank": 1, "level": 99, "xp": 200000000},
        {"id": 15, "name": "Mining", "rank": 8, "level": 99, "xp": 200000000},
        {"id": 16, "name": "Herblore", "rank": 3, "level": 99, "xp": 200000000},
        {"id": 17, "name": "Agility", "rank": 9, "level": 99, "xp": 200000000},
        {"id": 18, "name": "Thieving", "rank": 97, "level": 99, "xp": 200000000},
        {"id": 19, "name": "Slayer", "rank": 1, "level": 99, "xp": 200000000},
        {"id": 20, "name": "Farming", "rank": 34, "level": 99, "xp": 200000000},
        {"id": 21, "name": "Runecraft", "rank": 10, "level": 99, "xp": 200000000},
        {"id": 22, "name": "Hunter", "rank": 17, "level": 99, "xp": 200000000},
        {"id": 23, "name": "Construction", "rank": 3, "level": 99, "xp": 200000000},
    ],
    "activities": [
        {"id": 0, "name": "League Points", "rank": -1, "score": -1},
        {"id": 1, "name": "Deadman Points", "rank": -1, "score": -1},
        {"id": 2, "name": "Bounty Hunter - Hunter", "rank": -1, "score": -1},
        {"id": 3, "name": "Bounty Hunter - Rogue", "rank": -1, "score": -1},
        {"id": 4, "name": "Bounty Hunter (Legacy) - Hunter", "rank": 14220, "score": 5},
        {"id": 5, "name": "Bounty Hunter (Legacy) - Rogue", "rank": 1031, "score": 3},
        {"id": 6, "name": "Clue Scrolls (all)", "rank": 121, "score": 6063},
        {"id": 7, "name": "Clue Scrolls (beginner)", "rank": 2634, "score": 371},
        {"id": 8, "name": "Clue Scrolls (easy)", "rank": 601, "score": 1211},
        {"id": 9, "name": "Clue Scrolls (medium)", "rank": 3124, "score": 587},
        {"id": 10, "name": "Clue Scrolls (hard)", "rank": 28, "score": 2663},
        {"id": 11, "name": "Clue Scrolls (elite)", "rank": 42, "score": 816},
        {"id": 12, "name": "Clue Scrolls (master)", "rank": 227, "score": 415},
        {"id": 13, "name": "LMS - Rank", "rank": 1765, "score": 3033},
        {"id": 14, "name": "PvP Arena - Rank", "rank": 273, "score": 3045},
        {"id": 15, "name": "Soul Wars Zeal", "rank": 2225, "score": 3813},
        {"id": 16, "name": "Rifts closed", "rank": 4260, "score": 574},
        {"id": 17, "name": "Colosseum Glory", "rank": 181, "score": 7439},
        {"id": 18, "name": "Abyssal Sire", "rank": 2102, "score": 1112},
        {"id": 19, "name": "Alchemical Hydra", "rank": 3035, "score": 2198},
        {"id": 20, "name": "Artio", "rank": 2524, "score": 871},
        {"id": 21, "name": "Barrows Chests", "rank": 1132, "score": 1761},
        {"id": 22, "name": "Bryophyta", "rank": 2230, "score": 121},
        {"id": 23, "name": "Callisto", "rank": 6000, "score": 279},
        {"id": 24, "name": "Calvar'ion", "rank": -1, "score": -1},
        {"id": 25, "name": "Cerberus", "rank": 1038, "score": 2356},
        {"id": 26, "name": "Chambers of Xeric", "rank": 4042, "score": 774},
        {
            "id": 27,
            "name": "Chambers of Xeric: Challenge Mode",
            "rank": 4777,
            "score": 72,
        },
        {"id": 28, "name": "Chaos Elemental", "rank": 5710, "score": 176},
        {"id": 29, "name": "Chaos Fanatic", "rank": 2903, "score": 281},
        {"id": 30, "name": "Commander Zilyana", "rank": 293, "score": 1946},
        {"id": 31, "name": "Corporeal Beast", "rank": 3449, "score": 498},
        {"id": 32, "name": "Crazy Archaeologist", "rank": 982, "score": 580},
        {"id": 33, "name": "Dagannoth Prime", "rank": 29, "score": 4290},
        {"id": 34, "name": "Dagannoth Rex", "rank": 64, "score": 3483},
        {"id": 35, "name": "Dagannoth Supreme", "rank": 35, "score": 4266},
        {"id": 36, "name": "Deranged Archaeologist", "rank": 5972, "score": 50},
        {"id": 37, "name": "Duke Sucellus", "rank": 4806, "score": 372},
        {"id": 38, "name": "General Graardor", "rank": 14988, "score": 557},
        {"id": 39, "name": "Giant Mole", "rank": 835, "score": 3010},
        {"id": 40, "name": "Grotesque Guardians", "rank": 26, "score": 4593},
        {"id": 41, "name": "Hespori", "rank": 222, "score": 711},
        {"id": 42, "name": "Kalphite Queen", "rank": 139, "score": 2417},
        {"id": 43, "name": "King Black Dragon", "rank": 708, "score": 1559},
        {"id": 44, "name": "Kraken", "rank": 3848, "score": 3768},
        {"id": 45, "name": "Kree'Arra", "rank": 3686, "score": 687},
        {"id": 46, "name": "K'ril Tsutsaroth", "rank": 5567, "score": 473},
        {"id": 47, "name": "Lunar Chests", "rank": -1, "score": -1},
        {"id": 48, "name": "Mimic", "rank": 167, "score": 40},
        {"id": 49, "name": "Nex", "rank": 3779, "score": 782},
        {"id": 50, "name": "Nightmare", "rank": 1894, "score": 101},
        {"id": 51, "name": "Phosani's Nightmare", "rank": 818, "score": 647},
        {"id": 52, "name": "Obor", "rank": 1815, "score": 72},
        {"id": 53, "name": "Phantom Muspah", "rank": 938, "score": 658},
        {"id": 54, "name": "Sarachnis", "rank": 1226, "score": 1000},
        {"id": 55, "name": "Scorpia", "rank": 2820, "score": 287},
        {"id": 56, "name": "Scurrius", "rank": -1, "score": -1},
        {"id": 57, "name": "Skotizo", "rank": 8, "score": 1069},
        {"id": 58, "name": "Sol Heredit", "rank": -1, "score": -1},
        {"id": 59, "name": "Spindel", "rank": 3390, "score": 600},
        {"id": 60, "name": "Tempoross", "rank": 7021, "score": 424},
        {"id": 61, "name": "The Gauntlet", "rank": 13394, "score": 51},
        {"id": 62, "name": "The Corrupted Gauntlet", "rank": 2230, "score": 1112},
        {"id": 63, "name": "The Leviathan", "rank": 4332, "score": 115},
        {"id": 64, "name": "The Whisperer", "rank": 5081, "score": 43},
        {"id": 65, "name": "Theatre of Blood", "rank": 5808, "score": 251},
        {"id": 66, "name": "Theatre of Blood: Hard Mode", "rank": 2947, "score": 13},
        {"id": 67, "name": "Thermonuclear Smoke Devil", "rank": 6, "score": 12828},
        {"id": 68, "name": "Tombs of Amascut", "rank": 2813, "score": 171},
        {"id": 69, "name": "Tombs of Amascut: Expert Mode", "rank": 467, "score": 605},
        {"id": 70, "name": "TzKal-Zuk", "rank": 2880, "score": 2},
        {"id": 71, "name": "TzTok-Jad", "rank": 102, "score": 86},
        {"id": 72, "name": "Vardorvis", "rank": 209, "score": 2698},
        {"id": 73, "name": "Venenatis", "rank": 604, "score": 1112},
        {"id": 74, "name": "Vet'ion", "rank": 1303, "score": 699},
        {"id": 75, "name": "Vorkath", "rank": 6, "score": 27740},
        {"id": 76, "name": "Wintertodt", "rank": 68, "score": 8069},
        {"id": 77, "name": "Zalcano", "rank": 203, "score": 1632},
        {"id": 78, "name": "Zulrah", "rank": 108, "score": 6465},
    ],
}

RIP_DIDDEBOY_RESPONSE = {
    "skills": [
        {"id": 0, "name": "Overall", "rank": 617342, "level": 1795, "xp": 819190759},
        {"id": 1, "name": "Attack", "rank": -1, "level": 1, "xp": -1},
        {"id": 2, "name": "Defence", "rank": -1, "level": 1, "xp": -1},
        {"id": 3, "name": "Strength", "rank": -1, "level": 1, "xp": -1},
        {"id": 4, "name": "Hitpoints", "rank": -1, "level": 1, "xp": -1},
        {"id": 5, "name": "Ranged", "rank": -1, "level": 1, "xp": -1},
        {"id": 6, "name": "Prayer", "rank": -1, "level": 1, "xp": -1},
        {"id": 7, "name": "Magic", "rank": -1, "level": 1, "xp": -1},
        {"id": 8, "name": "Cooking", "rank": 6117, "level": 99, "xp": 68911756},
        {"id": 9, "name": "Woodcutting", "rank": 3709, "level": 99, "xp": 50044318},
        {"id": 10, "name": "Fletching", "rank": 818, "level": 99, "xp": 113603254},
        {"id": 11, "name": "Fishing", "rank": 11193, "level": 99, "xp": 21837372},
        {"id": 12, "name": "Firemaking", "rank": 921, "level": 99, "xp": 167610374},
        {"id": 13, "name": "Crafting", "rank": 5175, "level": 99, "xp": 18572612},
        {"id": 14, "name": "Smithing", "rank": 3781, "level": 99, "xp": 29672448},
        {"id": 15, "name": "Mining", "rank": 3412, "level": 99, "xp": 32905483},
        {"id": 16, "name": "Herblore", "rank": 8338, "level": 99, "xp": 15528751},
        {"id": 17, "name": "Agility", "rank": 999, "level": 99, "xp": 33390767},
        {"id": 18, "name": "Thieving", "rank": 2673, "level": 99, "xp": 73591858},
        {"id": 19, "name": "Slayer", "rank": 95663, "level": 99, "xp": 14014070},
        {"id": 20, "name": "Farming", "rank": 1954, "level": 99, "xp": 97659121},
        {"id": 21, "name": "Runecraft", "rank": 1115, "level": 99, "xp": 43954034},
        {"id": 22, "name": "Hunter", "rank": 10769, "level": 99, "xp": 21836147},
        {"id": 23, "name": "Construction", "rank": 2073, "level": 99, "xp": 15960705},
    ],
    "activities": [
        {"id": 0, "name": "League Points", "rank": -1, "score": -1},
        {"id": 1, "name": "Deadman Points", "rank": -1, "score": -1},
        {"id": 2, "name": "Bounty Hunter - Hunter", "rank": -1, "score": -1},
        {"id": 3, "name": "Bounty Hunter - Rogue", "rank": -1, "score": -1},
        {"id": 4, "name": "Bounty Hunter (Legacy) - Hunter", "rank": -1, "score": -1},
        {"id": 5, "name": "Bounty Hunter (Legacy) - Rogue", "rank": -1, "score": -1},
        {"id": 6, "name": "Clue Scrolls (all)", "rank": 13264, "score": 1644},
        {"id": 7, "name": "Clue Scrolls (beginner)", "rank": 446, "score": 1034},
        {"id": 8, "name": "Clue Scrolls (easy)", "rank": 8330, "score": 515},
        {"id": 9, "name": "Clue Scrolls (medium)", "rank": 151315, "score": 91},
        {"id": 10, "name": "Clue Scrolls (hard)", "rank": 819267, "score": 4},
        {"id": 11, "name": "Clue Scrolls (elite)", "rank": -1, "score": -1},
        {"id": 12, "name": "Clue Scrolls (master)", "rank": -1, "score": -1},
        {"id": 13, "name": "LMS - Rank", "rank": -1, "score": -1},
        {"id": 14, "name": "PvP Arena - Rank", "rank": 6252, "score": 2753},
        {"id": 15, "name": "Soul Wars Zeal", "rank": -1, "score": -1},
        {"id": 16, "name": "Rifts closed", "rank": 13228, "score": 617},
        {"id": 17, "name": "Colosseum Glory", "rank": -1, "score": -1},
        {"id": 18, "name": "Abyssal Sire", "rank": -1, "score": -1},
        {"id": 19, "name": "Alchemical Hydra", "rank": -1, "score": -1},
        {"id": 20, "name": "Artio", "rank": -1, "score": -1},
        {"id": 21, "name": "Barrows Chests", "rank": -1, "score": -1},
        {"id": 22, "name": "Bryophyta", "rank": -1, "score": -1},
        {"id": 23, "name": "Callisto", "rank": -1, "score": -1},
        {"id": 24, "name": "Calvar'ion", "rank": -1, "score": -1},
        {"id": 25, "name": "Cerberus", "rank": -1, "score": -1},
        {"id": 26, "name": "Chambers of Xeric", "rank": -1, "score": -1},
        {
            "id": 27,
            "name": "Chambers of Xeric: Challenge Mode",
            "rank": -1,
            "score": -1,
        },
        {"id": 28, "name": "Chaos Elemental", "rank": -1, "score": -1},
        {"id": 29, "name": "Chaos Fanatic", "rank": -1, "score": -1},
        {"id": 30, "name": "Commander Zilyana", "rank": -1, "score": -1},
        {"id": 31, "name": "Corporeal Beast", "rank": -1, "score": -1},
        {"id": 32, "name": "Crazy Archaeologist", "rank": -1, "score": -1},
        {"id": 33, "name": "Dagannoth Prime", "rank": -1, "score": -1},
        {"id": 34, "name": "Dagannoth Rex", "rank": -1, "score": -1},
        {"id": 35, "name": "Dagannoth Supreme", "rank": -1, "score": -1},
        {"id": 36, "name": "Deranged Archaeologist", "rank": -1, "score": -1},
        {"id": 37, "name": "Duke Sucellus", "rank": -1, "score": -1},
        {"id": 38, "name": "General Graardor", "rank": -1, "score": -1},
        {"id": 39, "name": "Giant Mole", "rank": -1, "score": -1},
        {"id": 40, "name": "Grotesque Guardians", "rank": -1, "score": -1},
        {"id": 41, "name": "Hespori", "rank": -1, "score": -1},
        {"id": 42, "name": "Kalphite Queen", "rank": -1, "score": -1},
        {"id": 43, "name": "King Black Dragon", "rank": -1, "score": -1},
        {"id": 44, "name": "Kraken", "rank": -1, "score": -1},
        {"id": 45, "name": "Kree'Arra", "rank": -1, "score": -1},
        {"id": 46, "name": "K'ril Tsutsaroth", "rank": -1, "score": -1},
        {"id": 47, "name": "Lunar Chests", "rank": -1, "score": -1},
        {"id": 48, "name": "Mimic", "rank": -1, "score": -1},
        {"id": 49, "name": "Nex", "rank": -1, "score": -1},
        {"id": 50, "name": "Nightmare", "rank": -1, "score": -1},
        {"id": 51, "name": "Phosani's Nightmare", "rank": -1, "score": -1},
        {"id": 52, "name": "Obor", "rank": -1, "score": -1},
        {"id": 53, "name": "Phantom Muspah", "rank": -1, "score": -1},
        {"id": 54, "name": "Sarachnis", "rank": -1, "score": -1},
        {"id": 55, "name": "Scorpia", "rank": -1, "score": -1},
        {"id": 56, "name": "Scurrius", "rank": -1, "score": -1},
        {"id": 57, "name": "Skotizo", "rank": -1, "score": -1},
        {"id": 58, "name": "Sol Heredit", "rank": -1, "score": -1},
        {"id": 59, "name": "Spindel", "rank": -1, "score": -1},
        {"id": 60, "name": "Tempoross", "rank": 12254, "score": 581},
        {"id": 61, "name": "The Gauntlet", "rank": -1, "score": -1},
        {"id": 62, "name": "The Corrupted Gauntlet", "rank": -1, "score": -1},
        {"id": 63, "name": "The Leviathan", "rank": -1, "score": -1},
        {"id": 64, "name": "The Whisperer", "rank": -1, "score": -1},
        {"id": 65, "name": "Theatre of Blood", "rank": -1, "score": -1},
        {"id": 66, "name": "Theatre of Blood: Hard Mode", "rank": -1, "score": -1},
        {"id": 67, "name": "Thermonuclear Smoke Devil", "rank": -1, "score": -1},
        {"id": 68, "name": "Tombs of Amascut", "rank": -1, "score": -1},
        {"id": 69, "name": "Tombs of Amascut: Expert Mode", "rank": -1, "score": -1},
        {"id": 70, "name": "TzKal-Zuk", "rank": -1, "score": -1},
        {"id": 71, "name": "TzTok-Jad", "rank": -1, "score": -1},
        {"id": 72, "name": "Vardorvis", "rank": -1, "score": -1},
        {"id": 73, "name": "Venenatis", "rank": -1, "score": -1},
        {"id": 74, "name": "Vet'ion", "rank": -1, "score": -1},
        {"id": 75, "name": "Vorkath", "rank": -1, "score": -1},
        {"id": 76, "name": "Wintertodt", "rank": 511, "score": 6094},
        {"id": 77, "name": "Zalcano", "rank": -1, "score": -1},
        {"id": 78, "name": "Zulrah", "rank": -1, "score": -1},
    ],
}

LYNX_TITAN_RESPONSE = {
    "skills": [
        {"id": 0, "name": "Overall", "rank": 1, "level": 2277, "xp": 4600000000},
        {"id": 1, "name": "Attack", "rank": 15, "level": 99, "xp": 200000000},
        {"id": 2, "name": "Defence", "rank": 28, "level": 99, "xp": 200000000},
        {"id": 3, "name": "Strength", "rank": 18, "level": 99, "xp": 200000000},
        {"id": 4, "name": "Hitpoints", "rank": 7, "level": 99, "xp": 200000000},
        {"id": 5, "name": "Ranged", "rank": 8, "level": 99, "xp": 200000000},
        {"id": 6, "name": "Prayer", "rank": 11, "level": 99, "xp": 200000000},
        {"id": 7, "name": "Magic", "rank": 30, "level": 99, "xp": 200000000},
        {"id": 8, "name": "Cooking", "rank": 154, "level": 99, "xp": 200000000},
        {"id": 9, "name": "Woodcutting", "rank": 15, "level": 99, "xp": 200000000},
        {"id": 10, "name": "Fletching", "rank": 12, "level": 99, "xp": 200000000},
        {"id": 11, "name": "Fishing", "rank": 9, "level": 99, "xp": 200000000},
        {"id": 12, "name": "Firemaking", "rank": 48, "level": 99, "xp": 200000000},
        {"id": 13, "name": "Crafting", "rank": 4, "level": 99, "xp": 200000000},
        {"id": 14, "name": "Smithing", "rank": 3, "level": 99, "xp": 200000000},
        {"id": 15, "name": "Mining", "rank": 24, "level": 99, "xp": 200000000},
        {"id": 16, "name": "Herblore", "rank": 5, "level": 99, "xp": 200000000},
        {"id": 17, "name": "Agility", "rank": 24, "level": 99, "xp": 200000000},
        {"id": 18, "name": "Thieving", "rank": 12, "level": 99, "xp": 200000000},
        {"id": 19, "name": "Slayer", "rank": 2, "level": 99, "xp": 200000000},
        {"id": 20, "name": "Farming", "rank": 19, "level": 99, "xp": 200000000},
        {"id": 21, "name": "Runecraft", "rank": 6, "level": 99, "xp": 200000000},
        {"id": 22, "name": "Hunter", "rank": 4, "level": 99, "xp": 200000000},
        {"id": 23, "name": "Construction", "rank": 4, "level": 99, "xp": 200000000},
    ],
    "activities": [
        {"id": 0, "name": "League Points", "rank": -1, "score": -1},
        {"id": 1, "name": "Deadman Points", "rank": -1, "score": -1},
        {"id": 2, "name": "Bounty Hunter - Hunter", "rank": -1, "score": -1},
        {"id": 3, "name": "Bounty Hunter - Rogue", "rank": -1, "score": -1},
        {"id": 4, "name": "Bounty Hunter (Legacy) - Hunter", "rank": -1, "score": -1},
        {"id": 5, "name": "Bounty Hunter (Legacy) - Rogue", "rank": -1, "score": -1},
        {"id": 6, "name": "Clue Scrolls (all)", "rank": 832280, "score": 22},
        {"id": 7, "name": "Clue Scrolls (beginner)", "rank": -1, "score": -1},
        {"id": 8, "name": "Clue Scrolls (easy)", "rank": -1, "score": -1},
        {"id": 9, "name": "Clue Scrolls (medium)", "rank": -1, "score": -1},
        {"id": 10, "name": "Clue Scrolls (hard)", "rank": 517041, "score": 22},
        {"id": 11, "name": "Clue Scrolls (elite)", "rank": -1, "score": -1},
        {"id": 12, "name": "Clue Scrolls (master)", "rank": -1, "score": -1},
        {"id": 13, "name": "LMS - Rank", "rank": -1, "score": -1},
        {"id": 14, "name": "PvP Arena - Rank", "rank": -1, "score": -1},
        {"id": 15, "name": "Soul Wars Zeal", "rank": -1, "score": -1},
        {"id": 16, "name": "Rifts closed", "rank": -1, "score": -1},
        {"id": 17, "name": "Colosseum Glory", "rank": -1, "score": -1},
        {"id": 18, "name": "Abyssal Sire", "rank": -1, "score": -1},
        {"id": 19, "name": "Alchemical Hydra", "rank": -1, "score": -1},
        {"id": 20, "name": "Artio", "rank": -1, "score": -1},
        {"id": 21, "name": "Barrows Chests", "rank": -1, "score": -1},
        {"id": 22, "name": "Bryophyta", "rank": -1, "score": -1},
        {"id": 23, "name": "Callisto", "rank": -1, "score": -1},
        {"id": 24, "name": "Calvar'ion", "rank": -1, "score": -1},
        {"id": 25, "name": "Cerberus", "rank": -1, "score": -1},
        {"id": 26, "name": "Chambers of Xeric", "rank": -1, "score": -1},
        {
            "id": 27,
            "name": "Chambers of Xeric: Challenge Mode",
            "rank": -1,
            "score": -1,
        },
        {"id": 28, "name": "Chaos Elemental", "rank": -1, "score": -1},
        {"id": 29, "name": "Chaos Fanatic", "rank": -1, "score": -1},
        {"id": 30, "name": "Commander Zilyana", "rank": -1, "score": -1},
        {"id": 31, "name": "Corporeal Beast", "rank": -1, "score": -1},
        {"id": 32, "name": "Crazy Archaeologist", "rank": -1, "score": -1},
        {"id": 33, "name": "Dagannoth Prime", "rank": -1, "score": -1},
        {"id": 34, "name": "Dagannoth Rex", "rank": -1, "score": -1},
        {"id": 35, "name": "Dagannoth Supreme", "rank": -1, "score": -1},
        {"id": 36, "name": "Deranged Archaeologist", "rank": -1, "score": -1},
        {"id": 37, "name": "Duke Sucellus", "rank": -1, "score": -1},
        {"id": 38, "name": "General Graardor", "rank": -1, "score": -1},
        {"id": 39, "name": "Giant Mole", "rank": -1, "score": -1},
        {"id": 40, "name": "Grotesque Guardians", "rank": -1, "score": -1},
        {"id": 41, "name": "Hespori", "rank": -1, "score": -1},
        {"id": 42, "name": "Kalphite Queen", "rank": -1, "score": -1},
        {"id": 43, "name": "King Black Dragon", "rank": -1, "score": -1},
        {"id": 44, "name": "Kraken", "rank": -1, "score": -1},
        {"id": 45, "name": "Kree'Arra", "rank": -1, "score": -1},
        {"id": 46, "name": "K'ril Tsutsaroth", "rank": -1, "score": -1},
        {"id": 47, "name": "Lunar Chests", "rank": -1, "score": -1},
        {"id": 48, "name": "Mimic", "rank": -1, "score": -1},
        {"id": 49, "name": "Nex", "rank": -1, "score": -1},
        {"id": 50, "name": "Nightmare", "rank": -1, "score": -1},
        {"id": 51, "name": "Phosani's Nightmare", "rank": -1, "score": -1},
        {"id": 52, "name": "Obor", "rank": -1, "score": -1},
        {"id": 53, "name": "Phantom Muspah", "rank": -1, "score": -1},
        {"id": 54, "name": "Sarachnis", "rank": -1, "score": -1},
        {"id": 55, "name": "Scorpia", "rank": -1, "score": -1},
        {"id": 56, "name": "Scurrius", "rank": -1, "score": -1},
        {"id": 57, "name": "Skotizo", "rank": -1, "score": -1},
        {"id": 58, "name": "Sol Heredit", "rank": -1, "score": -1},
        {"id": 59, "name": "Spindel", "rank": -1, "score": -1},
        {"id": 60, "name": "Tempoross", "rank": -1, "score": -1},
        {"id": 61, "name": "The Gauntlet", "rank": -1, "score": -1},
        {"id": 62, "name": "The Corrupted Gauntlet", "rank": -1, "score": -1},
        {"id": 63, "name": "The Leviathan", "rank": -1, "score": -1},
        {"id": 64, "name": "The Whisperer", "rank": -1, "score": -1},
        {"id": 65, "name": "Theatre of Blood", "rank": -1, "score": -1},
        {"id": 66, "name": "Theatre of Blood: Hard Mode", "rank": -1, "score": -1},
        {"id": 67, "name": "Thermonuclear Smoke Devil", "rank": -1, "score": -1},
        {"id": 68, "name": "Tombs of Amascut", "rank": -1, "score": -1},
        {"id": 69, "name": "Tombs of Amascut: Expert Mode", "rank": -1, "score": -1},
        {"id": 70, "name": "TzKal-Zuk", "rank": -1, "score": -1},
        {"id": 71, "name": "TzTok-Jad", "rank": 251, "score": 186},
        {"id": 72, "name": "Vardorvis", "rank": -1, "score": -1},
        {"id": 73, "name": "Venenatis", "rank": -1, "score": -1},
        {"id": 74, "name": "Vet'ion", "rank": -1, "score": -1},
        {"id": 75, "name": "Vorkath", "rank": -1, "score": -1},
        {"id": 76, "name": "Wintertodt", "rank": -1, "score": -1},
        {"id": 77, "name": "Zalcano", "rank": -1, "score": -1},
        {"id": 78, "name": "Zulrah", "rank": -1, "score": -1},
    ],
}

NEW_SKILL_OR_ACTIVITY_RESPONSE = {
    "skills": [
        {"id": 0, "name": "Overall", "rank": 1, "level": 2277, "xp": 4600000000},
        {"id": 1, "name": "Attack", "rank": 15, "level": 99, "xp": 200000000},
        {"id": 2, "name": "Defence", "rank": 28, "level": 99, "xp": 200000000},
        {"id": 3, "name": "Strength", "rank": 18, "level": 99, "xp": 200000000},
        {"id": 4, "name": "Hitpoints", "rank": 7, "level": 99, "xp": 200000000},
        {"id": 5, "name": "Ranged", "rank": 8, "level": 99, "xp": 200000000},
        {"id": 6, "name": "Prayer", "rank": 11, "level": 99, "xp": 200000000},
        {"id": 7, "name": "Magic", "rank": 30, "level": 99, "xp": 200000000},
        {"id": 8, "name": "Cooking", "rank": 154, "level": 99, "xp": 200000000},
        {"id": 9, "name": "Woodcutting", "rank": 15, "level": 99, "xp": 200000000},
        {"id": 10, "name": "Fletching", "rank": 12, "level": 99, "xp": 200000000},
        {"id": 11, "name": "Fishing", "rank": 9, "level": 99, "xp": 200000000},
        {"id": 12, "name": "Firemaking", "rank": 48, "level": 99, "xp": 200000000},
        {"id": 13, "name": "Crafting", "rank": 4, "level": 99, "xp": 200000000},
        {"id": 14, "name": "Smithing", "rank": 3, "level": 99, "xp": 200000000},
        {"id": 15, "name": "Mining", "rank": 24, "level": 99, "xp": 200000000},
        {"id": 16, "name": "Herblore", "rank": 5, "level": 99, "xp": 200000000},
        {"id": 17, "name": "Agility", "rank": 24, "level": 99, "xp": 200000000},
        {"id": 18, "name": "Thieving", "rank": 12, "level": 99, "xp": 200000000},
        {"id": 19, "name": "Slayer", "rank": 2, "level": 99, "xp": 200000000},
        {"id": 20, "name": "Farming", "rank": 19, "level": 99, "xp": 200000000},
        {"id": 21, "name": "Runecraft", "rank": 6, "level": 99, "xp": 200000000},
        {"id": 22, "name": "Hunter", "rank": 4, "level": 99, "xp": 200000000},
        {"id": 23, "name": "Construction", "rank": 4, "level": 99, "xp": 200000000},
    ],
    "activities": [
        {"id": 0, "name": "League Points", "rank": -1, "score": -1},
        {"id": 1, "name": "Deadman Points", "rank": -1, "score": -1},
        {"id": 2, "name": "Bounty Hunter - Hunter", "rank": -1, "score": -1},
        {"id": 3, "name": "Bounty Hunter - Rogue", "rank": -1, "score": -1},
        {"id": 4, "name": "Bounty Hunter (Legacy) - Hunter", "rank": -1, "score": -1},
        {"id": 5, "name": "Bounty Hunter (Legacy) - Rogue", "rank": -1, "score": -1},
        {"id": 6, "name": "Clue Scrolls (all)", "rank": 832280, "score": 22},
        {"id": 7, "name": "Clue Scrolls (beginner)", "rank": -1, "score": -1},
        {"id": 8, "name": "Clue Scrolls (easy)", "rank": -1, "score": -1},
        {"id": 9, "name": "Clue Scrolls (medium)", "rank": -1, "score": -1},
        {"id": 10, "name": "Clue Scrolls (hard)", "rank": 517041, "score": 22},
        {"id": 11, "name": "Clue Scrolls (elite)", "rank": -1, "score": -1},
        {"id": 12, "name": "Clue Scrolls (master)", "rank": -1, "score": -1},
        {"id": 13, "name": "LMS - Rank", "rank": -1, "score": -1},
        {"id": 14, "name": "PvP Arena - Rank", "rank": -1, "score": -1},
        {"id": 15, "name": "Soul Wars Zeal", "rank": -1, "score": -1},
        {"id": 16, "name": "Rifts closed", "rank": -1, "score": -1},
        {"id": 17, "name": "Colosseum Glory", "rank": -1, "score": -1},
        {"id": 18, "name": "Abyssal Sire", "rank": -1, "score": -1},
        {"id": 19, "name": "Alchemical Hydra", "rank": -1, "score": -1},
        {"id": 20, "name": "Artio", "rank": -1, "score": -1},
        {"id": 21, "name": "Barrows Chests", "rank": -1, "score": -1},
        {"id": 22, "name": "Bryophyta", "rank": -1, "score": -1},
        {"id": 23, "name": "Callisto", "rank": -1, "score": -1},
        {"id": 24, "name": "Calvar'ion", "rank": -1, "score": -1},
        {"id": 25, "name": "Cerberus", "rank": -1, "score": -1},
        {"id": 26, "name": "Chambers of Xeric", "rank": -1, "score": -1},
        {
            "id": 27,
            "name": "Chambers of Xeric: Challenge Mode",
            "rank": -1,
            "score": -1,
        },
        {"id": 28, "name": "Chaos Elemental", "rank": -1, "score": -1},
        {"id": 29, "name": "Chaos Fanatic", "rank": -1, "score": -1},
        {"id": 30, "name": "Commander Zilyana", "rank": -1, "score": -1},
        {"id": 31, "name": "Corporeal Beast", "rank": -1, "score": -1},
        {"id": 32, "name": "Crazy Archaeologist", "rank": -1, "score": -1},
        {"id": 33, "name": "Dagannoth Prime", "rank": -1, "score": -1},
        {"id": 34, "name": "Dagannoth Rex", "rank": -1, "score": -1},
        {"id": 35, "name": "Dagannoth Supreme", "rank": -1, "score": -1},
        {"id": 36, "name": "Deranged Archaeologist", "rank": -1, "score": -1},
        {"id": 37, "name": "Duke Sucellus", "rank": -1, "score": -1},
        {"id": 38, "name": "General Graardor", "rank": -1, "score": -1},
        {"id": 39, "name": "Giant Mole", "rank": -1, "score": -1},
        {"id": 40, "name": "Grotesque Guardians", "rank": -1, "score": -1},
        {"id": 41, "name": "Hespori", "rank": -1, "score": -1},
        {"id": 42, "name": "Kalphite Queen", "rank": -1, "score": -1},
        {"id": 43, "name": "King Black Dragon", "rank": -1, "score": -1},
        {"id": 44, "name": "Kraken", "rank": -1, "score": -1},
        {"id": 45, "name": "Kree'Arra", "rank": -1, "score": -1},
        {"id": 46, "name": "K'ril Tsutsaroth", "rank": -1, "score": -1},
        {"id": 47, "name": "Lunar Chests", "rank": -1, "score": -1},
        {"id": 48, "name": "Mimic", "rank": -1, "score": -1},
        {"id": 49, "name": "Nex", "rank": -1, "score": -1},
        {"id": 50, "name": "Nightmare", "rank": -1, "score": -1},
        {"id": 51, "name": "Phosani's Nightmare", "rank": -1, "score": -1},
        {"id": 52, "name": "Obor", "rank": -1, "score": -1},
        {"id": 53, "name": "Phantom Muspah", "rank": -1, "score": -1},
        {"id": 54, "name": "Sarachnis", "rank": -1, "score": -1},
        {"id": 55, "name": "Scorpia", "rank": -1, "score": -1},
        {"id": 56, "name": "Scurrius", "rank": -1, "score": -1},
        {"id": 57, "name": "Skotizo", "rank": -1, "score": -1},
        {"id": 58, "name": "Sol Heredit", "rank": -1, "score": -1},
        {"id": 59, "name": "Spindel", "rank": -1, "score": -1},
        {"id": 60, "name": "Tempoross", "rank": -1, "score": -1},
        {"id": 61, "name": "The Gauntlet", "rank": -1, "score": -1},
        {"id": 62, "name": "The Corrupted Gauntlet", "rank": -1, "score": -1},
        {"id": 63, "name": "The Leviathan", "rank": -1, "score": -1},
        {"id": 64, "name": "The Whisperer", "rank": -1, "score": -1},
        {"id": 65, "name": "Theatre of Blood", "rank": -1, "score": -1},
        {"id": 66, "name": "Theatre of Blood: Hard Mode", "rank": -1, "score": -1},
        {"id": 67, "name": "Thermonuclear Smoke Devil", "rank": -1, "score": -1},
        {"id": 68, "name": "Tombs of Amascut", "rank": -1, "score": -1},
        {"id": 69, "name": "Tombs of Amascut: Expert Mode", "rank": -1, "score": -1},
        {"id": 70, "name": "TzKal-Zuk", "rank": -1, "score": -1},
        {"id": 71, "name": "TzTok-Jad", "rank": 251, "score": 186},
        {"id": 72, "name": "Vardorvis", "rank": -1, "score": -1},
        {"id": 73, "name": "Venenatis", "rank": -1, "score": -1},
        {"id": 74, "name": "Vet'ion", "rank": -1, "score": -1},
        {"id": 75, "name": "Vorkath", "rank": -1, "score": -1},
        {"id": 76, "name": "Wintertodt", "rank": -1, "score": -1},
        {"id": 77, "name": "Zalcano", "rank": -1, "score": -1},
        {"id": 78, "name": "Zulrah", "rank": -1, "score": -1},
        {"id": 79, "name": "New Boss", "rank": -1, "score": -1},
    ],
}
